classes :
    ServiceLocator :
        class : \Gamping\Container
        singleton : true
    DbReader :
        class : \Berthe\DAL\DbReader
        singleton : true
        arguments : [ @MysqlAdapter ]
    DbWriter :
        class : \Berthe\DAL\DbWriter
        singleton : true
        arguments : [ @MysqlAdapter ]
    MysqlAdapter :
        class : Zend_Db_Adapter_Abstract
        singleton : true
        builder : \Zend_Db::factory
        arguments : [ %db.adapter, %db.params ]
    StoreArray :
        class : \Berthe\DAL\StoreArray
    TranslationEngine :
        class : Translation_Manager
        builder : \Gamping\Translation\InstanceCreator::factory
        singleton : true
        call :
            setEnableNotice : [ false ]
            registerStorage : [ dbString, @TranslationStringDatabaseEngine ]
    TranslationStringDatabaseEngine :
        class : \Gamping\Translation\StringDatabaseEngine
        singleton : true
        call :
            setDbAdapter : [ @DbWriter ]