classes:
    homeController:
        class: \Gamping\Controllers\Home
        interceptor : [ @GoogleAnalytics ]
        props :
            userManager : @UserManager
            parcelManager: @ParcelManager
            countryManager : @CountryManager
        call:
            setHomeService: [ @HomeService ]

    parcelController:
        class: \Gamping\Controllers\Parcel

    formController:
        class: \Gamping\Controllers\Form
        interceptor : [ @GoogleAnalytics ]
        call:
            setFormService: [ @ParcelFormService ]

    formSuccessController:
        class: \Gamping\Controllers\FormSuccess
        interceptor : [ @GoogleAnalytics ]
        props :
            userManager : @UserManager
            parcelManager: @ParcelManager

    searchController:
        class: \Gamping\Controllers\Search
        props :
            countryManager : @CountryManager
        call:
            setGeographicalService: [ @GeographicalService ]

    searchRegionsController:
        class: \Gamping\Controllers\Search\RegionsByCountry
        call:
            setGeographicalService: [ @GeographicalService ]

    parcelsSearchController:
        class: \Gamping\Controllers\Search\ParcelsSearch
        call:
            setGeographicalService: [ @GeographicalService ]
