classes:
    homeController:
        class: \Gamping\Controllers\Home
        interceptor : [ @GoogleAnalytics ]
        props :
            userManager : @UserManager
            parcelManager: @ParcelManager
            countryManager : @CountryManager
        call:
            setHomeService: [ @HomeService ]

    formController:
        class: \Gamping\Controllers\Form
        interceptor : [ @GoogleAnalytics ]
        call:
            setFormService: [ @ParcelFormService ]

    searchController:
        class: \Gamping\Controllers\Search
        props :
            countryManager : @CountryManager
        call:
            setGeographicalService: [ @GeographicalService ]

    searchRegionsController:
        class: \Gamping\Controllers\Search\RegionsByCountry
        call:
            setGeographicalService: [ @GeographicalService ]

    parcelsByRegionController:
        class: \Gamping\Controllers\Search\ParcelsByRegion
        call:
            setGeographicalService: [ @GeographicalService ]