include:
    - modules/user.yml
    - modules/country.yml
    - modules/picture.yml
    - modules/place.yml
    - modules/region.yml
    - modules/situation_geo.yml
    - modules/currency.yml
    - modules/activity.yml
    - modules/commodity.yml
    - modules/address.yml
    - modules/parcel.yml
    - modules/parcel_has_activity.yml
    - modules/parcel_has_commodity.yml
    - modules/parcel_has_situation_geo.yml
    - modules/parcel_has_picture.yml