parameters :
    db :
        adapter : PDO_MYSQL
        params :
            host : localhost
            port : 3306
            username : root
            password : weleanit
            dbname : weleanit
    facebook:
        key : facebook-app-key
    googleAnalytics:
        key : ga-key-thibaud

