parameters :
    db :
        adapter : PDO_MYSQL
        params :
            host : localhost
            port : 3306
            username : root
            password : gamping
            dbname : gamping