classes:
    ParcelFormService:
        class: \Gamping\Service\ParcelFormService
        arguments: [ @DbWriter ]
        call:
            setActivityManager: [ @ActivityManager ]
            setAddressManager: [ @AddressManager ]
            setCommodityManager: [ @CommodityManager ]
            setCurrencyManager: [ @CurrencyManager ]
            setParcelHasActivityManager: [ @ParcelHasActivityManager ]
            setParcelHasCommodityManager: [ @ParcelHasCommodityManager ]
            setParcelManager: [ @ParcelManager ]
            setCountryManager: [ @CountryManager ]
            setSituationGeoManager: [ @SituationGeoManager ]

    GeographicalService:
        class: \Gamping\Service\GeographicalService
        call:
            setCountryManager: [ @CountryManager ]
            setParcelManager : [ @ParcelManager ]
            setRegionManager: [ @RegionManager ]
            setUserManager: [ @UserManager ]
            setPictureManager: [ @PictureManager ]
            setParcelHasPictureManager: [ @ParcelHasPictureManager ]