<?php

$output = array();

/* @var $parcelView \View\Parcel\ParcelTile */
foreach ($this->parcelViews as $parcelView) {
    $parcel = $parcelView->getParcel();
    $user = $parcelView->getUser();
    
    $data['parcel'] = array(
        'id' => $parcel->getId(), 
        'name' => $parcel->getTitle(),
        'lat' => $parcel->getLatitude(),
        'lng' => $parcel->getLongitude(),
        'url' => sprintf('/parcel/id/%d/', $parcel->getId()));
    $data['user'] = array(
        'id' => $user->getId(), 
        'name' => $user->getFirstname(), 
        'picture' => ($parcelView->getUserPicture()) ? $parcelView->getUserPicture()->getUrl() : ""
    );
    
    $output[] = $data;
}

echo json_encode($output);