classes :
    PlaceHasSituationGeoManager :
        class : \Gamping\Model\PlaceHasSituationGeo\Manager
        call :
            setStorage : [ @PlaceHasSituationGeoStorage ]
            setValidator : [ @PlaceHasSituationGeoValidator ]
        interceptor : [ @ExceptionInterceptor ]
    PlaceHasSituationGeoValidator :
        class : \Gamping\Model\PlaceHasSituationGeo\Validator
    PlaceHasSituationGeoStorage :
        class : \Gamping\Model\PlaceHasSituationGeo\Storage
        call :
            setStoreVolatile : [ @PlaceHasSituationGeoStoreMemcached ]
            setStorePersistent : [ @PlaceHasSituationGeoStoreDatabase ]
            setStoreLevel1 : [ @StoreArray ]
    PlaceHasSituationGeoStoreMemcached :
        class : \Berthe\DAL\StoreMemcached
    PlaceHasSituationGeoStoreDatabase :
        class : \Berthe\DAL\StoreDatabase
        call :
            setReader : [ @PlaceHasSituationGeoReader ]
            setWriter : [ @PlaceHasSituationGeoWriter ]
    PlaceHasSituationGeoReader :
        class : \Gamping\Model\PlaceHasSituationGeo\Reader
        call :
            setDb : [ @DbReader ]
    PlaceHasSituationGeoWriter :
        class : \Gamping\Model\PlaceHasSituationGeo\Writer
        call :
            setDb : [ @DbWriter ]
