<div class="container">

    <div id="content" class="col-md-9">
        <div id="picture" data-backstretch-image= "http://www.gamping.com/wp-content/uploads/2013/11/P10109951-716x287.jpg"></div>

        <div class="row">
            <div class="col-md-9">
                <h1 class="h1"><?= $this->parcel->getTitle(); ?></h1>

                <p class="place-info">Saint Sylvain, France (Limousin)</p>

                <p class="allowing">
                    <?= t('Terrain pour :') ?>
                    <i class="allow-tent <?= $this->parcel->hasTents() ? '' : "not-allowed"; ?>" title="<?= t('Tentes autorisées') ?>"></i>
                    <i class="allow-caravan <?= $this->parcel->hasCaravans() ? '' : "not-allowed"; ?>" title="<?= t('Caravanes autorisées') ?>"></i>
                    <i class="allow-campingcar <?= $this->parcel->hasCampingCars() ? '' : "not-allowed"; ?>" title="<?= t('Camping car autorisés') ?>"></i>
                </p>

                <p><?= $this->parcel->getDescription(); ?></p>

                <hr />

                <h2 class="h2 services"><?= t('Services') ?></h2>






                <div class="row">
                    <?php
                    $commodities = $this->commodities;
                    $commoditiesPacked = array(array());
                    $pack = 0;
                    $increment = 0;
                    foreach($commodities as $commodity) {
                        if ($increment % 5 === 0) {
                            $pack++;
                        }
                        if (!array_key_exists($pack, $commoditiesPacked)) {
                            $commoditiesPacked[$pack] = array();
                        }

                        $commoditiesPacked[$pack][] = $commodity;
                        $increment++;
                    }


                    foreach($commoditiesPacked as $pack => $commoditiesInPack) {
                        ?>
                        <div class="col-md-4">
                            <ul class="available">
                                <?php
                                foreach($commoditiesInPack as $commodity) {
                                    if (array_key_exists($commodity->getId(), $this->phc)) {
                                        $checked = 'class="yes"';
                                    }
                                    else {
                                        $checked = '';
                                    }
                                    ?>
                                    <li <?= $checked; ?>><?= $commodity->getName(); ?></li>
                                    <?php
                                }
                                ?>
                            </ul>
                        </div>
                        <?php
                    }
                    ?>
                </div>

                <hr />

                <h2 class="h2 services"><?= t('Activités') ?></h2>


                <div class="row">
                    <?php
                    $activities = $this->activities;
                    $activitiesPacked = array(array());
                    $pack = 0;
                    $increment = 0;
                    foreach($activities as $activity) {
                        if ($increment % 5 === 0) {
                            $pack++;
                        }
                        if (!array_key_exists($pack, $activitiesPacked)) {
                            $activitiesPacked[$pack] = array();
                        }

                        $activitiesPacked[$pack][] = $activity;
                        $increment++;
                    }


                    foreach($activitiesPacked as $pack => $activitiesInPack) {
                        ?>
                        <div class="col-md-4">
                            <ul class="available">
                                <?php
                                foreach($activitiesInPack as $activity) {
                                    if (array_key_exists($activity->getId(), $this->pha)) {
                                        $checked = 'class="yes"';
                                    }
                                    else {
                                        $checked = '';
                                    }
                                    ?>
                                    <li <?= $checked; ?>><?= $activity->getName(); ?></li>
                                    <?php
                                }
                                ?>
                            </ul>
                        </div>
                        <?php
                    }
                    ?>
                </div>




            </div>

            <div class="col-md-3 r">

                <!-- display price here. Need icon :( -->

                <p class="notice"><em><?= t('Les prix sont indicatifs. Contactez l\'hôte même si le prix ne vous convient pas.'); ?></em></p>

                <a href="#" class="contact-host"><?= t("Contacter l'hôte") ?></a>


            </div>
        </div>



    </div>
    <div class="col-md-3 sidebar">
        <div class="widget">
            <h2 class="h2"><?= t('Témoignages'); ?></h2>
            <div class="testimonial img-left nopadding" itemscope itemtype="http://data-vocabulary.org/Review">
                <div class="head">
                    <img src="http://www.gamping.com/wp-content/authors/herve.blanco@orange.fr-1145-1383587191.jpg" >
                    <h3 class="h3"><strong itemprop="reviewer"><?= t('Jean Marc</strong>, gamper'); ?></h3>
                </div>
                <q itemprop="description"><?= t('My money\'s in that office, right? If she start giving me some bullshit about it ain\'t there, and we got to go someplace else and get it, I\'m gonna shoot you in the head then and there.'); ?></q>
            </div>
        </div>

        <div class="widget">
            <h2 class="h2"><?= t('Quelques chiffres'); ?></h2>
            <ul>
                <li><?= t('Déjà plus de <strong>250 gampeurs</strong> ont été mis en relation avec un hôte.'); ?></li>
                <li><?= t('Gamping.com, c\'est <strong>250</strong> hôtes dans 11 pays !'); ?></li>
            </ul>
        </div>
    </div>
</div>
