<div class="container">

    <div id="content" class="col-md-9">
        <div id="picture" data-backstretch-image= "http://www.gamping.com/wp-content/uploads/2013/11/P10109951-716x287.jpg"></div>
    </div>
    <div class="col-md-3 sidebar">
        <div class="widget">
            <h2 class="h2"><?= t('Témoignages'); ?></h2>
            <div class="testimonial img-left nopadding" itemscope itemtype="http://data-vocabulary.org/Review">
                <div class="head">
                    <img src="http://www.gamping.com/wp-content/authors/herve.blanco@orange.fr-1145-1383587191.jpg" >
                    <h3 class="h3"><strong itemprop="reviewer"><?= t('Jean Marc</strong>, gamper'); ?></h3>
                </div>
                <q itemprop="description"><?= t('My money\'s in that office, right? If she start giving me some bullshit about it ain\'t there, and we got to go someplace else and get it, I\'m gonna shoot you in the head then and there.'); ?></q>
            </div>
        </div>

        <div class="widget">
            <h2 class="h2"><?= t('Quelques chiffres'); ?></h2>
            <ul>
                <li><?= t('Déjà plus de <strong>250 gampeurs</strong> ont été mis en relation avec un hôte.'); ?></li>
                <li><?= t('Gamping.com, c\'est <strong>250</strong> hôtes dans 11 pays !'); ?></li>
            </ul>
        </div>
    </div>
</div>
