<div class="container">

    <div id="content" class="col-md-9">

        <h1 class="h1">Proposez votre terrain en 1 minute. (gratuit)</h1>

        <form action="?" class="smart-form row" method="post">
            <div>
                <fieldset class="who col-md-6">
                    <h2 class="h2">Qui voulez vous recevoir ?</h2>
                    <div data-form-choices="multiple">
                        <ul class="hosting_type">
                            <li class="tent"><a href="#" data-name="hosting_tent">Tente</a></li>
                            <li class="caravan"><a href="#" data-name="hosting_caravan">Caravan</a></li>
                            <li class="campingcar"><a href="#" data-name="hosting_campingcar">Camping car</a></li>
                        </ul>
                        <input type="hidden" name="hosting_tent" value="0" />
                        <input type="hidden" name="hosting_caravan" value="0" />
                        <input type="hidden" name="hosting_campingcar" value="0" />
                    </div>

                    <select name="count">
                        <option value="1">1 personne</option>
                        <option value="2">2 personnes</option>
                        <!-- aller jusqu'à 10 -->
                    </select>
                </fieldset>

                <fieldset class="situation col-md-6">
                    <h2 class="h2">Situation</h2>
                    <ul class="checkboxlist">
                        <li>
                            <label for="situation_sea">
                                <input type="checkbox" name="situation_sea" id="situation_sea" />
                                Mer
                            </label>
                        </li>
                        <li>
                            <label for="situation_sea">
                                <input type="checkbox" name="situation_sea" id="situation_sea" />
                                Ville
                            </label>
                        </li>
                        <li>
                            <label for="situation_sea">
                                <input type="checkbox" name="situation_sea" id="situation_sea" />
                                Montagne
                            </label>
                        </li>
                        <li>
                            <label for="situation_sea">
                                <input type="checkbox" name="situation_sea" id="situation_sea" />
                                Campagne
                            </label>
                        </li>
                    </ul>
                </fieldset>
            </div>
            <fieldset class="services col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2">Services</h2>
                        <p>Indiquez quels services seront à disposition des gampeurs durant leur séjour.</p>
                    </div>
                    <div class="col-md-3">
                        <ul class="checkboxlist">
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Mer
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Ville
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Montagne
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Campagne
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <ul class="checkboxlist">
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Mer
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Ville
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Montagne
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Campagne
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <ul class="checkboxlist">
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Mer
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Ville
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Montagne
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Campagne
                                </label>
                            </li>
                        </ul>
                    </div>
                </div>
            </fieldset>

            <fieldset class="activities col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2">Activités</h2>
                        <p>Précisez les activités possibles à proximité de votre emplacement pour donner encore plus de visibilité à votre annonce.</p>
                    </div>
                    <div class="col-md-3">
                        <ul class="checkboxlist">
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Mer
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Ville
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Montagne
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Campagne
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <ul class="checkboxlist">
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Mer
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Ville
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Montagne
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Campagne
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <ul class="checkboxlist">
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Mer
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Ville
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Montagne
                                </label>
                            </li>
                            <li>
                                <label for="situation_sea">
                                    <input type="checkbox" name="situation_sea" id="situation_sea" />
                                    Campagne
                                </label>
                            </li>
                        </ul>
                    </div>
                </div>
            </fieldset>
            <fieldset class="prices col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2">Prix</h2>
                        <div class="error">Ca ne va pas du tout</div>
                    </div>

                    <div class="col-md-12">
                        <label for="price_base" class="inline"><input type="number" name="price_base" id="price_base" /> Prix 1 emplacement + 1 adulte</label>
                    </div>
                    <div class="col-md-12">
                        <label for="price_extra" class="inline"><input type="number" name="price_extra" id="price_extra" /> Prix par personne suppémentaire</label>
                    </div>
                    <div class="col-md-12">
                        <label for="currency" class="block">Devise :</label>
                        <select name="currency" id="currency">
                            <option value="eur">&euro; Euros</option>
                            <option value="dol">&#36; Dollard</option>
                        </select>
                    </div>
                </div>
            </fieldset>

            <fieldset class="address col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2">Adresse</h2>
                        <p>Cette adresse ne sera pas visible publiquement mais permettra de positionner approximativement votre emplacement sur des cartes ou plus tard pour permettre la recherche par géolocalisation.</p>
                    </div>
                    <div class="col-md-6">
                        <select name="country" id="country">
                            <option value="">Choisir un pays</option>
                        </select>
                    </div>
                    <div class="col-md-6">
                        <select name="state" id="state">
                            <option value="">Choisir une région</option>
                        </select>
                    </div>
                    <div class="col-md-12">
                        <input type="text" name="address" id="address" placeholder="Adresse" class="long" />
                        <input type="text" name="address" id="address" placeholder="Adresse (suite - optionnel)" class="long" />
                        <input type="text" name="zip" id="zip" placeholder="Code postal" class="small" />
                        <input type="text" name="city" id="city" placeholder="Ville" class="small" />
                    </div>
                </div>
            </fieldset>
           <div class="button-row">
                <button type="submit" name="submit" value="true" class="submit">Envoyer !</button>
            </div>
        </form>
    </div>
    <div class="col-md-3 sidebar">

        <div class="widget">
            <h2 class="h2">Témoignages</h2>
            <div class="testimonial img-left nopadding" itemscope itemtype="http://data-vocabulary.org/Review">
                <div class="head">
                    <img src="http://www.gamping.com/wp-content/authors/herve.blanco@orange.fr-1145-1383587191.jpg" >
                    <h3 class="h3"><strong itemprop="reviewer">Jean Marc</strong>, gamper</h3>
                </div>
                <q itemprop="description">My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there.</q>
            </div>
        </div>

        <div class="widget">
            <h2 class="h2">Quelques chiffres</h2>
            <ul>
                <li>Déjà plus de <strong>250 gampeurs</strong> ont été mis en relation avec un hôte.</li>
                <li>Gamping.com, c'est <strong>250</strong> hôtes dans 11 pays !</li>
            </ul>
        </div>
    </div>
</div>
