<?php
function get($dataContainer, $key) {
    return isset($dataContainer[$key]) ? $dataContainer[$key] : null;
};

$data = $this->formData;

?>
<div class="container">

    <div id="content" class="col-md-9">

        <h1 class="h1"><?= t('Proposez votre terrain en 1 minute. (gratuit)'); ?></h1>

        <form action="?" class="smart-form row" method="post">
            <div>
                <fieldset class="who col-md-6">
                    <h2 class="h2"><?= t('Qui voulez vous recevoir ?'); ?></h2>

                    <?php
                    if ($this->errorHosting === false) {
                        $hostingClass = " hide";
                    }
                    ?>
                    <div class="error <?= $hostingClass; ?>"><?= t('Il faut au moins 1 type d\'emplacement') ?></div>

                    <div data-form-choices="multiple">
                        <ul class="hosting_type">
                            <li class="tent"><a href="#" data-name="hosting_tent" <?= get($data, 'hosting_tent') == 1 ? 'class="selected"' : '' ?>><?= t('Tente'); ?></a></li>
                            <li class="caravan"><a href="#" data-name="hosting_caravan" <?= get($data, 'hosting_caravan') == 1 ? 'class="selected"' : '' ?>><?= t('Caravan'); ?></a></li>
                            <li class="campingcar"><a href="#" data-name="hosting_campingcar" <?= get($data, 'hosting_campingcar') == 1 ? 'class="selected"' : '' ?>><?= t('Camping car'); ?></a></li>
                        </ul>
                        <input type="hidden" name="hosting_tent" value="<?= get($data, 'hosting_tent') == 1 ? 1 : 0 ?>" />
                        <input type="hidden" name="hosting_caravan" value="<?= get($data, 'hosting_tent') == 1 ? 1 : 0 ?>" />
                        <input type="hidden" name="hosting_campingcar" value="<?= get($data, 'hosting_tent') == 1 ? 1 : 0 ?>" />
                    </div>

                    <select name="count">
                        <option value="1"><?= '1' . ' ' . t('personne'); ?></option>
                        <?php
                        for ($i=2; $i <= 20; $i++) {
                            ?>
                            <option value="<?= $i; ?>" <?= get($data, 'count') == $i ? 'selected="selected"' : '' ?>><?= $i . ' ' . t('personnes'); ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </fieldset>

                <fieldset class="situation col-md-6">
                    <h2 class="h2"><?= t('Situation'); ?></h2>
                    <ul class="checkboxlist">
                        <?php
                        foreach($this->situationGeos as $situationGeo) {
                            $situationList = get($data, 'situation_geo');
                            if (is_array($situationList) && in_array($situationGeo->getId(), $situationList)) {
                                $checked = 'checked="checked"';
                            }
                            else {
                                $checked = '';
                            }
                            ?>
                            <li>
                                <label for="situation<?= $situationGeo->getId(); ?>">
                                    <input type="checkbox" name="situation_geo[]" id="situation<?= $situationGeo->getId(); ?>" value="<?= $situationGeo->getId(); ?>" <?= $checked ?>/>
                                    <?= $situationGeo->getName(); ?>
                                </label>
                            </li>
                            <?php
                        }
                        ?>
                    </ul>
                </fieldset>
            </div>
            <fieldset class="services col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2"><?= t('Services'); ?></h2>
                        <p><?= t('Indiquez quels services seront à disposition des gampeurs durant leur séjour.'); ?></p>
                    </div>

                    <?php
                    $commodities = $this->commodities;
                    $commoditiesPacked = array(array());
                    $pack = 0;
                    $increment = 0;
                    foreach($commodities as $commodity) {
                        if ($increment % 5 === 0) {
                            $pack++;
                        }
                        if (!array_key_exists($pack, $commoditiesPacked)) {
                            $commoditiesPacked[$pack] = array();
                        }

                        $commoditiesPacked[$pack][] = $commodity;
                        $increment++;
                    }


                    foreach($commoditiesPacked as $pack => $commoditiesInPack) {
                        ?>
                        <div class="col-md-3">
                            <ul class="checkboxlist">
                                <?php
                                foreach($commoditiesInPack as $commodity) {
                                    $list = get($data, 'commodities');
                                    if (is_array($list) && in_array($commodity->getId(), $list)) {
                                        $checked = 'checked="checked"';
                                    }
                                    else {
                                        $checked = '';
                                    }
                                    ?>
                                    <li>
                                        <label for="commodity<?= $commodity->getId(); ?>">
                                            <input type="checkbox" name="commodities[]" id="commodity<?= $commodity->getId(); ?>" value="<?= $commodity->getId(); ?>" <?= $checked ?> />
                                            <?= $commodity->getName(); ?>
                                        </label>
                                    </li>
                                    <?php
                                }
                                ?>
                            </ul>
                        </div>
                        <?php
                    }
                    ?>
                </div>
            </fieldset>

            <fieldset class="activities col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2"><?= t('Activités'); ?></h2>
                        <p><?= t('Précisez les activités possibles à proximité de votre emplacement pour donner encore plus de visibilité à votre annonce.'); ?></p>
                    </div>

                    <?php
                    $activities = $this->activities;
                    $activitiesPacked = array(array());
                    $pack = 0;
                    $increment = 0;
                    foreach($activities as $activity) {
                        if ($increment % 5 === 0) {
                            $pack++;
                        }
                        if (!array_key_exists($pack, $commoditiesPacked)) {
                            $activitiesPacked[$pack] = array();
                        }

                        $activitiesPacked[$pack][] = $activity;
                        $increment++;
                    }


                    foreach($activitiesPacked as $pack => $activitiesInPack) {
                        ?>
                        <div class="col-md-3">
                            <ul class="checkboxlist">
                                <?php
                                foreach($activitiesInPack as $activity) {
                                    $list = get($data, 'activities');
                                    if (is_array($list) && in_array($activity->getId(), $list)) {
                                        $checked = 'checked="checked"';
                                    }
                                    else {
                                        $checked = '';
                                    }
                                    ?>
                                    <li>
                                        <label for="activity<?= $activity->getId(); ?>">
                                            <input type="checkbox" name="activities[]" id="activity<?= $activity->getId(); ?>" value="<?= $activity->getId(); ?>" <?= $checked ?> />
                                            <?= $activity->getName(); ?>
                                        </label>
                                    </li>
                                    <?php
                                }
                                ?>
                            </ul>
                        </div>
                        <?php
                    }
                    ?>


                </div>
            </fieldset>
            <fieldset class="prices col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2"><?= t('Prix'); ?></h2>

                        <?php
                        if ($this->errorPrice === false) {
                            $priceClass = " hide";
                        }
                        ?>
                        <div class="error <?= $priceClass; ?>"><?= t('Les prix sont obligatoires') ?></div>

                    </div>

                    <div class="col-md-12">
                        <label for="price_base" class="inline"><input type="number" name="price_base" id="price_base" value="<?= get($data, 'price_base') ?>" /> <?= t('Prix 1 emplacement + 1 adulte'); ?></label>
                    </div>
                    <div class="col-md-12">
                        <label for="price_extra" class="inline"><input type="number" name="price_extra" id="price_extra" value="<?= get($data, 'price_extra') ?>" /> <?= t('Prix par personne suppémentaire'); ?></label>
                    </div>
                    <div class="col-md-12">
                        <label for="currency" class="block"><?= t('Devise :'); ?></label>
                        <select name="currency" id="currency">
                            <?php
                            foreach($this->currencies as $currency) {
                                ?>
                                <option value="<?= $currency->getId(); ?>" <?= get($data, 'currency') == $currency->getId() ? 'selected="selected"' : '' ?>><?= $currency->getHtml() . ' ' . $currency->getName() ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </fieldset>

            <fieldset class="more-infos col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2"><?= t('Parlez-nous de votre terrain.'); ?></h2>

                        <?php
                        if ($this->errorTitle === false) {
                            $errorTitle = " hide";
                        }
                        ?>
                        <div class="error <?= $errorTitle; ?>"><?= t('Le titre est obligatoire') ?></div>

                        <?php
                        if ($this->errorDesc === false) {
                            $errorDesc = " hide";
                        }
                        ?>
                        <div class="error <?= $errorDesc; ?>"><?= t('La description est obligatoire') ?></div>

                        <input type="text" name="title" class="long" placeholder="<?= t('Titre de votre annonce') ?>" value="<?= get($data, 'title') ?>" />
                        <textarea name="description" placeholder="<?= t('Décrivez votre terrain pour vos futurs campeurs...'); ?>"><?= get($data, 'description') ?></textarea>
                        <textarea name="rules" placeholder="<?= t('Listez ici les règles que les campeurs devront respecter...'); ?>"><?= get($data, 'rules') ?></textarea>
                    </div>
                </div>
            </fieldset>

            <fieldset class="address col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2"><?= t('Adresse'); ?></h2>
                        <p><?= t('Cette adresse ne sera pas visible publiquement mais permettra de positionner approximativement votre emplacement sur des cartes ou plus tard pour permettre la recherche par géolocalisation.'); ?></p>

                        <?php
                        if ($this->errorAddress === false) {
                            $errorAddress = " hide";
                        }
                        ?>
                        <div class="error <?= $errorAddress; ?>"><?= t('Adresse incomplète. Seul le champ adresse2 est optionnel') ?></div>
                    </div>
                    <div class="col-md-6">
                        <select name="country" id="country">
                            <option value=""><?= t('Choisir un pays'); ?></option>
                            <?php
                            foreach($this->countries as $country) {
                                ?>
                                <option value="<?= $country->getId(); ?>" <?= get($data, 'country') == $country->getId() ? 'selected="selected"' : '' ?>><?= $country->getName(); ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>
                    <div class="col-md-6">
                        <select name="state" id="state">
                            <option value=""><?= t('Choisir une région'); ?></option>
                        </select>
                    </div>
                    <div class="col-md-12">
                        <input type="text" name="address1" id="address1" placeholder="<?= t('Adresse'); ?>" class="long" value="<?= get($data, 'address1') ?>" />
                        <input type="text" name="address2" id="address2" placeholder="<?= t('Adresse (suite - optionnel)'); ?>" class="long" value="<?= get($data, 'address2') ?>" />
                        <input type="text" name="zip" id="zip" placeholder="<?= t('Code postal'); ?>" class="small" value="<?= get($data, 'zip') ?>" />
                        <input type="text" name="city" id="city" placeholder="<?= t('Ville'); ?>" class="small" value="<?= get($data, 'city') ?>" />
                    </div>
                </div>
            </fieldset>

            <fieldset class="more-user col-md-12">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="h2"><?= t('Pour vous joindre'); ?></h2>
                        <p><?= t('Indiquez les informations relatives à votre compte'); ?></p>

                        <?php
                        if ($this->errorUser === false) {
                            $errorUser = " hide";
                        }
                        ?>
                        <div class="error <?= $errorUser; ?>"><?= t('Informations incomplètes') ?></div>
                    </div>
                    <div class="col-md-5">
                        <input type="text" class="long" name="firstname" id="firstname" placeholder="<?= t('Votre prénom') ?>" value="<?= get($data, 'firstname') ?>" />
                    </div>
                    <div class="col-md-5">
                        <input type="text" class="long" name="lastname" id="lastname" placeholder="<?= t('Votre nom') ?>" value="<?= get($data, 'lastname') ?>" />
                    </div>
                    <div class="col-md-2"></div>
                    <div class="col-md-12">
                        <input type="text" class="long" name="email" id="email" placeholder="<?= t('Votre email') ?>" value="<?= get($data, 'email') ?>" />
                    </div>
                    <div class="col-md-12">
                        <input type="password" class="long" name="password" id="password" placeholder="<?= t('Votre mot de passe') ?>" value="<?= get($data, 'password') ?>" />
                    </div>
                </div>
            </fieldset>

            <div class="button-row">
                <button type="submit" name="submit" value="true" class="submit"><?= t('Envoyer !'); ?></button>
            </div>
        </form>
    </div>
    <div class="col-md-3 sidebar">

        <div class="widget">
            <h2 class="h2"><?= t('Témoignages'); ?></h2>
            <div class="testimonial img-left nopadding" itemscope itemtype="http://data-vocabulary.org/Review">
                <div class="head">
                    <img src="http://www.gamping.com/wp-content/authors/herve.blanco@orange.fr-1145-1383587191.jpg" >
                    <h3 class="h3"><strong itemprop="reviewer"><?= t('Jean Marc</strong>, gamper'); ?></h3>
                </div>
                <q itemprop="description"><?= t('My money\'s in that office, right? If she start giving me some bullshit about it ain\'t there, and we got to go someplace else and get it, I\'m gonna shoot you in the head then and there.'); ?></q>
            </div>
        </div>

        <div class="widget">
            <h2 class="h2"><?= t('Quelques chiffres'); ?></h2>
            <ul>
                <li><?= t('Déjà plus de <strong>250 gampeurs</strong> ont été mis en relation avec un hôte.'); ?></li>
                <li><?= t('Gamping.com, c\'est <strong>250</strong> hôtes dans 11 pays !'); ?></li>
            </ul>
        </div>
    </div>
</div>
