<div id="banner" data-backstretch-image="/images/gamping.jpg">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <label for="place">
                    Trouvez un emplacement de camping.
                </label>
                <form method="get" action="#" id="searchform">
                    <input type="text" id="place" name="place" placeholder="Où allez vous ?" class="form-control" />
                    <input type="hidden" id="placeid" name="placeid" />
                    <input type="submit" value="Rechercher" />
                    <select id="places_values">
                        <option value="/acores">Açores</option>
                        <option value="/afrique-du-sud">Afrique du sud</option>
                        <option value="/albanie">Albanie</option>
                        <option value="/argentine">Argentine</option>
                        <option value="/armenie">Arménie</option>
                        <option value="/australie">Australie</option>
                        <option value="/autriche">Autriche</option>
                        <option value="/azerbaidjan">Azerbaïdjan</option>
                        <option value="/bangladesh">Bangladesh</option>
                        <option value="/belize">Belize</option>
                        <option value="/benin">Bénin</option>
                        <option value="/bhoutan">Bhoutan</option>
                        <option value="/birmanie">Birmanie</option>
                        <option value="/bolivie">Bolivie</option>
                        <option value="/botswana">Botswana</option>
                        <option value="/bresil">Brésil</option>
                        <option value="/bulgarie">Bulgarie</option>
                        <option value="/burkina-faso">Burkina Faso</option>
                        <option value="/cambodge">Cambodge</option>
                        <option value="/cameroun">Cameroun</option>
                        <option value="/canada">Canada</option>
                        <option value="/chili">Chili</option>
                        <option value="/chine">Chine</option>
                        <option value="/colombie">Colombie</option>
                        <option value="/congo">Congo</option>
                        <option value="/coree-du-sud">Corée du Sud</option>
                        <option value="/corse">Corse</option>
                        <option value="/costa-rica">Costa Rica</option>
                        <option value="/croatie">Croatie</option>
                        <option value="/cuba">Cuba</option>
                        <option value="/danemark">Danemark</option>
                        <option value="/ecosse">Ecosse</option>
                        <option value="/egypte">Egypte</option>
                        <option value="/equateur">Equateur</option>
                        <option value="/estonie">Estonie</option>
                        <option value="/etats-unis">Etats-Unis</option>
                        <option value="/ethiopie">Ethiopie</option>
                        <option value="/finlande">Finlande</option>
                        <option value="/france">France</option>
                        <option value="/georgie">Géorgie</option>
                        <option value="/ghana">Ghana</option>
                        <option value="/grece">Grèce</option>
                        <option value="/groenland">Groenland</option>
                        <option value="/guadeloupe">Guadeloupe</option>
                        <option value="/guatemala">Guatemala</option>
                        <option value="/guyane">Guyane</option>
                        <option value="/hawai">Hawaï</option>
                        <option value="/hongrie">Hongrie</option>
                        <option value="/ile-maurice">Île Maurice</option>
                        <option value="/iles-canaries">Iles Canaries</option>
                        <option value="/inde">Inde</option>
                        <option value="/indonesie">Indonésie</option>
                        <option value="/irlande">Irlande</option>
                        <option value="/islande">Islande</option>
                        <option value="/israel">Israël</option>
                        <option value="/jamaique">Jamaïque</option>
                        <option value="/jordanie">Jordanie</option>
                        <option value="/kazakhstan">Kazakhstan</option>
                        <option value="/kenya">Kenya</option>
                        <option value="/kirghizistan">Kirghizistan</option>
                        <option value="/laos">Laos</option>
                        <option value="/lettonie">Lettonie</option>
                        <option value="/liban">Liban</option>
                        <option value="/lituanie">Lituanie</option>
                        <option value="/madagascar">Madagascar</option>
                        <option value="/madere">Madère</option>
                        <option value="/maldives">Maldives</option>
                        <option value="/maroc">Maroc</option>
                        <option value="/mayotte">Mayotte</option>
                        <option value="/mexique">Mexique</option>
                        <option value="/moldavie">Moldavie</option>
                        <option value="/mongolie">Mongolie</option>
                        <option value="/montenegro">Montenegro</option>
                        <option value="/mozambique">Mozambique</option>
                        <option value="/namibie">Namibie</option>
                        <option value="/nepal">Népal</option>
                        <option value="/nicaragua">Nicaragua</option>
                        <option value="/norvege">Norvège</option>
                        <option value="/nouvelle-caledonie">Nouvelle Calédonie</option>
                        <option value="/nouvelle-zelande">Nouvelle Zélande</option>
                        <option value="/oman">Oman</option>
                        <option value="/ouzbekistan">Ouzbekistan</option>
                        <option value="/panama">Panama</option>
                        <option value="/perou">Pérou</option>
                        <option value="/philippines">Philippines</option>
                        <option value="/pologne">Pologne</option>
                        <option value="/polynesie-francaise">Polynésie Francaise</option>
                        <option value="/portugal">Portugal</option>
                        <option value="/republique-tcheque">République Tchèque</option>
                        <option value="/reunion">Réunion</option>
                        <option value="/rodrigues">Rodrigues</option>
                        <option value="/roumanie">Roumanie</option>
                        <option value="/russie">Russie</option>
                        <option value="/rwanda">Rwanda</option>
                        <option value="/salvador">Salvador</option>
                        <option value="/seychelles">Seychelles</option>
                        <option value="/sicile">Sicile</option>
                        <option value="/slovaquie">Slovaquie</option>
                        <option value="/slovenie">Slovénie</option>
                        <option value="/sri-lanka">Sri Lanka</option>
                        <option value="/suede">Suède</option>
                        <option value="/suisse">Suisse</option>
                        <option value="/tadjikistan">Tadjikistan</option>
                        <option value="/tanzanie">Tanzanie</option>
                        <option value="/thailande">Thaïlande</option>
                        <option value="/tibet">Tibet</option>
                        <option value="/togo">Togo</option>
                        <option value="/tunisie">Tunisie</option>
                        <option value="/turkmenistan">Turkmenistan</option>
                        <option value="/turquie">Turquie</option>
                        <option value="/ukraine">Ukraine</option>
                        <option value="/uruguay">Uruguay</option>
                        <option value="/venezuela">Venezuela</option>
                        <option value="/vietnam">Vietnam</option>
                        <option value="/zanzibar">Zanzibar</option>
                    </select>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">

        <div id="content" class="col-md-12">
            <div class="row">
                <div class="col-md-8">

                    <article itemscope itemtype="http://schema.org/Article">

                        <div class="row">
                            <div class="col-md-12">
                                <header><h2 class="h1">Qu'est ce que le Gamping ?</h2></header>
                                <aside>
                                    <p class="highlight">Le gamping (garden camping), c'est réserver un terrain chez un particulier partout dans le monde pour y camper. Ou gagner de l'argent en louant votre propre terrain.</p>
                                </aside>
                            </div>
                        </div>
                        <div id="what" class="row" itemprop="articleBody">
                            <div class="col-md-6">
                                <div class="row becore-guest">
                                    <div class="col-md-4 hidden-xs hidden-sm decorator">
                                    </div>
                                    <div class="col-md-8">
                                        <h3 class="h3">Partir gamper</h3>
                                        <p>Pour partir gimper, faire de nouvelles rencontres et découvrir de nouveaux horizons, c'est facile !</p>
                                        <ol>
                                            <li>Trouvez un terrain.</li>
                                            <li>Réservez-le avec l'hôte.</li>
                                            <li>Bon voyage !</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row becore-host">
                                    <div class="col-md-4 hidden-xs hidden-sm decorator">
                                    </div>
                                    <div class="col-md-8">
                                        <h3 class="h3">Devenir hôte</h3>
                                        <p>Pour devenir hôte et accueillir des gampeurs contre rémunération, rien de plus facile !</p>
                                        <ol>
                                            <li>Référencez votre terrain.</li>
                                            <li>Recevez des demandes de réservation.</li>
                                            <li>Accueillez vos invités.</li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="hosts" class="row">
                            <div class="col-md-12">
                                <h2 class="h2">Ils vous accueillent chez eux</h2>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="hostcard">
                                            <a href="#" title=""><img src="http://www.gamping.com/wp-content/authors/m.a.ccinfos@orange.fr-865-1376763439.jpg" title="Myriam L., hote pour gamping" ></a>
                                            <h3 class="h4"><a href="#" title="">Myriam L.</a></h3>
                                            <p>Votre hôte</p>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="hostcard">
                                            <a href="#" title=""><img src="http://www.gamping.com/wp-content/authors/herve.blanco@orange.fr-1145-1383587191.jpg"  title="Myriam L., hote pour gamping"></a>
                                            <h3 class="h4"><a href="#" title="">Tilap L.</a></h3>
                                            <p>Votre hôte</p>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="hostcard">
                                            <a href="#" title=""><img src="http://www.gamping.com/wp-content/authors/myriam.loubriat@hotmail.fr-353-1375099136.jpg"  title="Myriam L., hote pour gamping"></a>
                                            <h3 class="h4"><a href="#">Olivier M.</a></h3>
                                            <p>Votre hôte</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </article>
                </div>

                <section class="col-md-4 testimonial-list">
                    <h2 class="h1">Ils ont gampé</h2>
                    <p>Témoignages de campeurs ayant trouvé des hôtes grace à Gamping.com :</p>
                    <div class="testimonial img-left" itemscope itemtype="http://data-vocabulary.org/Review">
                        <di class="row">
                            <div class="head">
                                <img src="http://www.gamping.com/wp-content/authors/herve.blanco@orange.fr-1145-1383587191.jpg" >
                                <h3 class="h3"><strong itemprop="reviewer">Jean Marc</strong>, gamper</h3>
                            </div>
                            <q itemprop="description">My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there.</q>
                        </div>
                    </article>
                    <div class="testimonial img-right" itemscope itemtype="http://data-vocabulary.org/Review">
                        <di class="row">
                            <div class="head">
                                <img src="http://www.gamping.com/wp-content/authors/jp.31@free.fr-1108-1380964847.jpg" >
                                <h3 class="h3"><strong itemprop="reviewer">Jean Marc</strong>, gamper</h3>
                            </div>
                            <q itemprop="description">My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there.</q>
                        </div>
                    </article>
                </section>
            </div>
            <div class="row">
                <div class="col-md-12 cta-large">
                    <strong>Rejoignez la première communauté de gamping au monde !</strong> <a href="#">Proposez un terrain</a>
                </div>
            </div>
            <section class="reasons">

                <header class="row">
                    <div class="col-md-12">
                        <h2 class="h1">9 bonnes raisons de devenir hôte</h1>
                    </div>
                </header>

                <div class="row">
                    <div class="col-md-4 reason reason-1">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-2">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Gagner de l'argent</h3>
                                <p>Accumulez un peu de sous pour vous offrir des petits extras !</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-3">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Vivre plus confortablement</h3>
                                <p>Vous profiterez aussi des investissements réalisés pour les campeurs.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 reason reason-1">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-2">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-3">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 reason reason-1">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-2">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-3">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div class="row">
                <div class="col-md-12 cta-large">
                    <strong>Créez avec nous une nouvelle alternative d'hébergement !</strong> <a href="#">Proposez un terrain</a>
                </div>
            </div>
        </div>
    </div>
</div>