
<div id="banner" data-backstretch-image="/images/gamping.jpg">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <label for="place">
                    <?= t('Trouvez un emplacement de camping.'); ?>
                </label>
                <form method="get" action="#" id="searchform">
                    <input type="text" id="place" name="place" placeholder="Où allez vous ?" class="form-control" />
                    <input id="search_btn" type="submit" value="Rechercher" />
                    <select id="places_values">
                        <?php foreach($this->countries as $country): ?>
                            <option value="<?= $country->getComputername() ?>"><?= $country->getName() ?></option>
                        <?php endforeach; ?>
                    </select>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">

        <div id="content" class="col-md-12">
            <div class="row">
                <div class="col-md-8">

                    <article itemscope itemtype="http://schema.org/Article">

                        <div class="row">
                            <div class="col-md-12">
                                <header><h2 class="h1"><?= t('Qu\'est ce que le Gamping ?'); ?></h2></header>
                                <aside>
                                    <p class="highlight"><?= t('Le gamping (garden camping), c\'est réserver un terrain chez un particulier partout dans le monde pour y camper. Ou gagner de l\'argent en louant votre propre terrain.'); ?></p>
                                </aside>
                            </div>
                        </div>
                        <div id="what" class="row" itemprop="articleBody">
                            <div class="col-md-6">
                                <div class="row becore-guest">
                                    <div class="col-md-4 hidden-xs hidden-sm decorator">
                                    </div>
                                    <div class="col-md-8">
                                        <h3 class="h3"><?= t('Partir gamper'); ?></h3>
                                        <p><?= t('Pour partir gimper, faire de nouvelles rencontres et découvrir de nouveaux horizons, c\'est facile !'); ?></p>
                                        <ol>
                                            <li><?= t('Trouvez un terrain.'); ?></li>
                                            <li><?= t('Réservez-le avec l\'hôte.'); ?></li>
                                            <li><?= t('Bon voyage !'); ?></li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="row becore-host">
                                    <div class="col-md-4 hidden-xs hidden-sm decorator">
                                    </div>
                                    <div class="col-md-8">
                                        <h3 class="h3"><?= t('Devenir hôte'); ?></h3>
                                        <p><?= t('Pour devenir hôte et accueillir des gampeurs contre rémunération, rien de plus facile !'); ?></p>
                                        <ol>
                                            <li><?= t('Référencez votre terrain.'); ?></li>
                                            <li><?= t('Recevez des demandes de réservation.'); ?></li>
                                            <li><?= t('Accueillez vos invités.'); ?></li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="hosts" class="row">
                            <div class="col-md-12">
                                <h2 class="h2"><?= t('Ils vous accueillent chez eux'); ?></h2>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="hostcard">
                                            <a href="#" title=""><img src="http://www.gamping.com/wp-content/authors/m.a.ccinfos@orange.fr-865-1376763439.jpg" title="Myriam L., hote pour gamping" ></a>
                                            <h3 class="h4"><a href="#" title="">Myriam L.</a></h3>
                                            <p><?= t('Votre hôte'); ?></p>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="hostcard">
                                            <a href="#" title=""><img src="http://www.gamping.com/wp-content/authors/herve.blanco@orange.fr-1145-1383587191.jpg"  title="Myriam L., hote pour gamping"></a>
                                            <h3 class="h4"><a href="#" title="">Tilap L.</a></h3>
                                            <p><?= t('Votre hôte'); ?></p>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="hostcard">
                                            <a href="#" title=""><img src="http://www.gamping.com/wp-content/authors/myriam.loubriat@hotmail.fr-353-1375099136.jpg"  title="Myriam L., hote pour gamping"></a>
                                            <h3 class="h4"><a href="#">Olivier M.</a></h3>
                                            <p><?= t('Votre hôte'); ?></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </article>
                </div>

                <section class="col-md-4 testimonial-list">
                    <h2 class="h1"><?= t('Ils ont gampé'); ?></h2>
                    <p><?= t('Témoignages de campeurs ayant trouvé des hôtes grace à Gamping.com :'); ?></p>
                    <div class="testimonial img-left" itemscope itemtype="http://data-vocabulary.org/Review">
                        <di class="row">
                            <div class="head">
                                <img src="http://www.gamping.com/wp-content/authors/herve.blanco@orange.fr-1145-1383587191.jpg" >
                                <h3 class="h3"><strong itemprop="reviewer">Jean Marc</strong>, gamper</h3>
                            </div>
                            <q itemprop="description">My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there.</q>
                        </div>
                    </article>
                    <div class="testimonial img-right" itemscope itemtype="http://data-vocabulary.org/Review">
                        <di class="row">
                            <div class="head">
                                <img src="http://www.gamping.com/wp-content/authors/jp.31@free.fr-1108-1380964847.jpg" >
                                <h3 class="h3"><strong itemprop="reviewer">Jean Marc</strong>, gamper</h3>
                            </div>
                            <q itemprop="description">My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there.</q>
                        </div>
                    </article>
                </section>
            </div>
            <div class="row">
                <div class="col-md-12 cta-large">
                    <strong><?= t('Rejoignez la première communauté de gamping au monde !'); ?></strong> <a href="#"><?= t('Proposez un terrain'); ?></a>
                </div>
            </div>
            <section class="reasons">

                <header class="row">
                    <div class="col-md-12">
                        <h2 class="h1"><?= t('9 bonnes raisons de devenir hôte'); ?></h1>
                    </div>
                </header>

                <div class="row">
                    <div class="col-md-4 reason reason-1">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4"><?= t('Faire des rencontres'); ?></h3>
                                <p><?= t('Elargissez votre cercle d\'amis en accueillant des personnes du monde entier.'); ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-2">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4"><?= t('Gagner de l\'argent'); ?></h3>
                                <p><?= t('Accumulez un peu de sous pour vous offrir des petits extras !'); ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-3">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4"><?= t('Vivre plus confortablement'); ?></h3>
                                <p><?= t('Vous profiterez aussi des investissements réalisés pour les campeurs.'); ?></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 reason reason-1">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-2">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-3">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 reason reason-1">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-2">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 reason reason-3">
                        <div class="row">
                            <div class="col-md-2 l hidden-xs hidden-sm"></div>
                            <div class="col-md-10">
                                <h3 class="h4">Faire des rencontres</h3>
                                <p>Elargissez votre cercle d'amis en accueillant des personnes du monde entier.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <div class="row">
                <div class="col-md-12 cta-large">
                    <strong><?= t('Créez avec nous une nouvelle alternative d\'hébergement !'); ?></strong> <a href="#"><?= t('Proposez un terrain'); ?></a>
                </div>
            </div>
        </div>
    </div>
</div>