routes:
    home:
        pattern: "/"
        controller: homeController
        methods: [ get, post, put, delete ]
        output:
            html:
                view: app/views/home/home.phtml
                before-run: 
                after-run:
            json:
                before-run:
                after-run:
            xml:
                before-run:
                after-run: