default-layout: index
layouts:
    index: 
        template: app/views/index.phtml
        stylesheets:
            - [ "/style/style.less", less, screen ]
        scripts:
            head:
                - "/vendor/lessjs/less.js"
            bottom:
                - "//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"
                - "/js/layout.js"

routes:
    home:
        pattern: "/"
        controller: homeController
        methods: [ get ]
        scripts:
            bottom:
                - "/vendor/jquery-backstretch/jquery.backstretch.min.js"
                - "/vendor/jQuery-Autocomplete/src/jquery.autocomplete.min.js"
                - "/js/homepage.js"
        output:
            html:
                view: app/views/home/home.phtml

    form:
        pattern: "/register"
        controller: formController
        methods: [ get, post ]
        scripts:
            bottom:
                - "/js/add.js"
        output:
            html:
                view: app/views/form/form.phtml
                
    search:
        pattern: "/search"
        controller: searchController
        methods: [ get ]
        scripts:
            head:
                - "http://maps.google.com/maps/api/js?sensor=false"
            bottom:
                - "/js/search.js"
        output:
            html:
                view: app/views/search/search.phtml
                
    searchRegions:
        pattern: "/ajax/regions-by-country/id/{id}"
        controller: searchRegionsController
        methods: [ get ]
        output:
            json:
                view: app/views/search/regions.json.phtml
                
    searchParcels:
        pattern: "/ajax/parcels-by-region/id/{id}"
        controller: parcelsByRegionController
        methods: [ get ]
        output:
            json:
                view: app/views/search/parcels.json.phtml