default-layout: landing
layouts:
    landing: app/views/index.phtml

routes:
    home:
        pattern: "/"
        controller: homeController
        methods: [ get, post, put, delete ]
        output:
            html:
                layout: landing
                view: app/views/home/home.phtml
                before-run:
                after-run: [ afterRun ]
            json:
                before-run:
                after-run:
            xml:
                before-run:
                after-run:
                
    page:
        pattern: "/home"
        controller: homeController
        methods: [ get, post, put, delete ]
        output:
            html:
                view: app/views/home/home.phtml
                before-run: 
                after-run:
            json:
                before-run:
                after-run:
            xml:
                before-run:
                after-run: