ALTER TABLE parcel MODIFY COLUMN id INT(11) UNSIGNED;
ALTER TABLE activity MODIFY COLUMN id INT(11) UNSIGNED;
ALTER TABLE commodity MODIFY COLUMN id INT(11) UNSIGNED;
ALTER TABLE language MODIFY COLUMN id INT(11) UNSIGNED;
ALTER TABLE translation MODIFY COLUMN id INT(11) UNSIGNED;
